apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtfoundry-vks.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/name: virtfoundry-vks
    app.kubernetes.io/component: manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: virtfoundry-vks
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: virtfoundry-vks
        app.kubernetes.io/component: manager
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}{{- if .Values.image.digest }}@{{ .Values.image.digest }}{{- else }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
            {{- if .Values.nodeAddress }}
            - --node-address={{ .Values.nodeAddress }}
            {{- end }}
            - --node-port={{ .Values.nodePort }}
          env:
            {{- if .Values.nodeAddress }}
            - name: VKS_NODE_ADDRESS
              value: {{ .Values.nodeAddress | quote }}
            {{- end }}
          ports:
            - containerPort: 8081
              name: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: virtfoundry-vks
{{- if .Values.serviceAccount.create }}
{{- end }}
